dist: trusty
sudo: required
os:
- linux
compiler:
- gcc
language:
- c
env:
  global: DATETIME=$(date +%Y%m%d-%H%M%S)
matrix:
  include:
  - os: linux
    dist: trusty
    env: TARGET=linux-amd64 EXTENSION=
  - os: linux
    dist: trusty
    env: TARGET=linux-armhf EXTENSION=
  - os: linux
    dist: trusty
    env: TARGET=linux-i686 EXTENSION=
  - os: linux
    dist: trusty
    env: TARGET=windows-x86 EXTENSION=.exe
  - os: linux
    dist: trusty
    env: TARGET=windows-x64 EXTENSION=.exe
before_install:
- openssl aes-256-cbc -K $encrypted_1c982bbffd8a_key -iv $encrypted_1c982bbffd8a_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- export | sort
- env | sort
- sudo apt-get update
- sudo apt-get -y install build-essential python-virtualenv python3-dev python3-pip
  ninja-build cmake gcc-multilib
- if [ ! -z "${TARGET##*arm*}" ]; then sudo apt install libcurl4-openssl-dev libpcre++-dev ; fi
- if [ -f /usr/include/curl/curlbuild.h ]; then sudo wget http://vison.andi.com.br/libcurl/curlbuild.h -O /usr/include/curl/curlbuild.h ; fi
- if [ -f /usr/include/curl/curlbuild.h ]; then sudo wget http://vison.andi.com.br/libcurl/curlbuild-32.h -O /usr/include/curl/curlbuild-32.h ; fi
- if [ -f /usr/include/curl/curlbuild.h ]; then sudo wget http://vison.andi.com.br/libcurl/curlbuild-64.h -O /usr/include/curl/curlbuild-64.h ; fi
- if [ -z "${TARGET##*win*}" ]; then sudo apt install mingw-w64 ; fi
- if [ -z "${TARGET##*arm*}" ]; then sudo apt install gcc-arm-linux-gnueabihf
  pkg-config-arm-linux-gnueabihf ; sudo apt-get -y remove libcurl.*-dev ;
  sudo apt-get -y remove libpcre*-dev ;fi
- virtualenv .venv --python=python3
- ". .venv/bin/activate"
- pip3 install --upgrade pip
- pip3 install -r requirements.txt
script:
- echo TARGET=${TARGET}
- mkdir build_${TARGET} || true
- meson build_${TARGET} --cross-file tools/cross-compilation/${TARGET}.txt
- ninja -v -C build_${TARGET}
- file build_${TARGET}/mvdsv${EXTENSION}
- eval "$(ssh-agent -s)"
- cp deploy_rsa ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- ssh-add ~/.ssh/id_rsa
addons:
  ssh_known_hosts:
  - nl.andi.com.br:22
deploy:
- provider: script
  skip_cleanup: true
  script: bash deploy.sh ${TARGET} ${EXTENSION}
  on:
    branch: master
